// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: ui_demo_lvgl

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void gerValueButton7(lv_event_t * e);
void gerValueButton8(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
