// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: ui_demo_lvgl

#include "ui.h"

void gerValueButton7(lv_event_t * e)
{
	// Your code here
}

void gerValueButton8(lv_event_t * e)
{
	// Your code here
}
